filebeat:
  config:
    modules:
      path: ${path.config}/modules.d/*.yml
      reload.enabled: false
  inputs:
  - type: log
    paths:
      - /var/log/python-test/test.log

# output.elasticsearch:
#   hosts: 'http://elasticsearch-service:9200'
  # username: '${ELASTICSEARCH_USERNAME:}'
  # password: '${ELASTICSEARCH_PASSWORD:}'

output.logstash:
  hosts: ["logstash-service:5044"]
